---
title: "Spatial clustering luego de venta"
output:
  html_notebook: default
---

# Cargamos librerías

```{r}
suppressMessages(library(tidyverse))
library(knitr)
library(kableExtra)
library(forcats)

```

# Cargamos archivos

Cargamos los archivos
```{r}
grifos_sc <- readRDS(here::here("data","processed","grifos_con_sc_razon_social.RDS"))
```

# Cálculo de SC a nivel razon social



Creamos variable de diferencia pre-post sc

```{r}



grifos_sc_1 <- grifos_sc %>% 
    mutate(diff_sc = sc_post - sc_pre,
           razon_social_sum = if_else(razon_social %in% c("REPSOL COMERCIAL S.A.C.", 
                                                          "COESTI S.A.", 
                                                          "PERUANA DE ESTACIONES DE SERVICIOS S.A.C."),
                                      razon_social,
                                      "OTRA RAZÓN"))

grifos_sc_1 %>% 
    group_by(razon_social_sum) %>%
    summarise(mean_diff_sc = mean(diff_sc),
              sd = sd(diff_sc),
              n = n())
```

Creamos los resúmenes

```{r}
df1 <- grifos_sc_1 %>% 
    filter(diff_sc != 0)  %>%
    group_by(razon_social_sum) %>%
    summarise(Promedio= mean(diff_sc),
              SD = sd(diff_sc),
              "Mínimo" = min(diff_sc),
              "Máximo" = max(diff_sc),
              "Numero de Obs." = n()) %>%
    mutate(razon_social_sum= fct_relevel(razon_social_sum, 
                                         "PERUANA DE ESTACIONES DE SERVICIOS S.A.C.",
                                         "COESTI S.A.", 
                                         "REPSOL COMERCIAL S.A.C.",
                                         "OTRA RAZÓN",
                                         "Todas las estaciones")) %>%
    arrange(razon_social_sum) %>%
    select(1, 6, 2, 3, 4, 5)


df2 <- grifos_sc_1 %>% 
    filter(diff_sc != 0)  %>%
    mutate(razon_social_sum = "TODAS LAS ESTACIONES") %>%
    group_by(razon_social_sum) %>%
    summarise(Promedio= mean(diff_sc),
              SD = sd(diff_sc),
              "Mínimo" = min(diff_sc),
              "Máximo" = max(diff_sc),
              "Numero de Obs." = n()) %>%
    select(1, 6, 2, 3, 4, 5)

df3 <- grifos_sc_1 %>% 
    filter(diff_sc == 0)  %>%
    group_by(razon_social_sum) %>%
    summarise("Numero de Obs." = n()) %>%
    mutate(razon_social_sum= fct_relevel(razon_social_sum, 
                                         "PERUANA DE ESTACIONES DE SERVICIOS S.A.C.",
                                         "COESTI S.A.", 
                                         "REPSOL COMERCIAL S.A.C.",
                                         "OTRA RAZÓN",
                                         "Todas las estaciones"),
           Promedio = 0) %>%
    arrange(razon_social_sum) 


df4 <- grifos_sc_1 %>% 
    filter(diff_sc == 0)  %>%
    mutate(razon_social_sum = "TODAS LAS ESTACIONES") %>%
    group_by(razon_social_sum) %>%
    summarise("Numero de Obs." = n()) %>%
    mutate(Promedio = 0) %>%
    arrange(razon_social_sum) 
```


Creamos la tabla

```{r}

options(knitr.kable.NA = '-')

bind_rows(df1, df2, df3, df4) %>%
    rename("Razón Social" = razon_social_sum) %>%
    kable(format = "html", 
          digits = c(0, 0, 3, 3, 3, 3),
          caption = "Varición en medida de agrupamiento espacial pre y post compra") %>%
    kable_styling(full_width = FALSE, position = "left") %>%
    pack_rows("Grupo de Tratamiento", 1, 5) %>%
    pack_rows("Grupo de Control", 6, 10)
```

# Estadísticas descriptivas para tesis

Generamos los archivos con precios y caracterísiticas 
```{r}
precios_db5 <- readRDS(here::here("data", "processed", "data_diesel_mensual.rds")) %>%
  filter(`año` >= 2017,
         codigo_de_osinergmin %in% grifos_sc$codigo_de_osinergmin) %>% 
  mutate(dia = 1) %>% 
  unite(fecha, dia, mes, `año`, sep = "-", remove = FALSE) %>%
  select(-dia) %>%
  filter(mes != 13,
         precio_de_venta > 6)

  
data_db5 <- left_join(grifos_sc, precios_db5, by = "codigo_de_osinergmin") 


precios_g90 <- readRDS(here::here("data", "processed", "data_g90_mensual.rds")) %>%
  filter(`año` >= 2017,
         codigo_de_osinergmin %in% grifos_sc$codigo_de_osinergmin) %>% 
  mutate(dia = 1) %>% 
  unite(fecha, dia, mes, `año`, sep = "-", remove = FALSE) %>%
  select(-dia) %>%
  filter(mes != 13,
         precio_de_venta > 6)

  
data_g90 <- left_join(grifos_sc, precios_g90, by = "codigo_de_osinergmin") 
```

Calculamos el precio promedio de cada uno
```{r}
precios_db5 %>% 
  summarise(`Precio promedio DB5` = mean(precio_de_venta),
            `SD` = sd(precio_de_venta),
            `min` = min(precio_de_venta),
            `max` = max(precio_de_venta))

hist(precios_db5$precio_de_venta)

data_db5 %>% filter(precio_de_venta < 8) %>% 
  select( codigo_de_osinergmin, razon_social, precio_de_venta, distrito, fecha)
```
```{r}
prices <- readRDS(here::here("data","processed","data_2005_2018_clean.rds"))
prices %>% 
  filter(codigo_de_osinergmin == 45240,
         producto == "DIESEL") %>%
  ggplot(aes(x = fecha_hora, y = precio_de_venta)) +
  geom_point()
prices %>% 
  filter(codigo_de_osinergmin == 45240,
         producto == "DIESEL",
         precio_de_venta < 7) %>% 
  select(fecha_hora,precio_de_venta)
```

