---
title: "Gráfico tendencias precios"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

# Cargamos librerías

```{r}
library(tidyverse)
library(lubridate)
source(here::here("R","funcion05_balancear-panel.R"), encoding = "UTF-8")
'%ni%' <- Negate('%in%')
library(did)
library(ggtext)
library(tidyquant)
'%ni%' <- Negate('%in%')
library(patchwork)
library(flextable)
```

# Temas y carga de datos
```{r}
tema_grafica <- theme_bw() + 
  theme(
    panel.spacing.x = unit(0.8, "cm"),
    legend.background = element_blank(),
    legend.title = element_text(face = "bold", size = 10),
    legend.text = element_text(colour = "black"),
    # legend.key = element_rect(colour = "black", size = 0.5),
    legend.key = element_blank(), 
    axis.title = element_text(face = "bold"),
    legend.position = "bottom")
 
f_labels <- data.frame(producto = c("G90", "DIESEL"), label = c("", "Venta de Pecsa"))

cols1 <- c(
  "PRIMAX" = "#f1c40f",
  "PECSA"  = "#e74c3c",
  "VECINA" = "#2ecc71",
  "NO VECINA" = "#5a5353"
)

data_total_semanal <- readRDS(file = here::here("data", "processed", "data-final-regresiones_semanal.rds")) %>% 
  mutate(semana_cont = if_else(año == 2017, semana, semana + 53))

data_total_mensual <- readRDS(file = here::here("data", "processed", "data-final-regresiones.rds"))

formato_comun <- list(
  ylim(10, 13),
  # geom_vline(
  #   xintercept = dmy("15/01/2018"),
  #   linetype = "dashed",
  #   size = 0.5, color = "grey55"
  # ),
  geom_rect(data = data.frame(xmin = dmy("01-01-2018"),
                              xmax = dmy("01-02-2018"),
                              ymin = -Inf,
                              ymax = Inf),
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            fill = "grey", alpha = 0.5),
  geom_text(
    x = dmy("01/02/2018"), y = -Inf, vjust = -0.9,
    hjust = -0.1, aes(label = label), data = f_labels,
    color = "grey55", fontface = "bold"
  )
  # scale_color_brewer(palette = "Set1")
)

#' Lista de grifos que son vecinos a estación de PECSA 
#' 

data_total <- data_total_mensual

lista_vecinos_pecsa <- data_total %>% 
  filter(vecino_pecsa_thiessen == 1) %>%
  distinct(codigo_de_osinergmin) %>% 
  pull()

lista_vecinos_primax <- data_total %>% 
  # filter(vecino_primax_thiessen == 1) %>%
  filter(vecino_pecsa_thiessen == 1) %>% 
  distinct(codigo_de_osinergmin) %>% 
  pull()

# lista_vecinos_km <- data_total %>% 
# filter(vecino_pecsa_dist_did == 1) %>%
#   distinct(codigo_de_osinergmin) %>% 
#   pull()

distritos_con_pecsa <- data_total %>% 
  distinct(distrito, tipo_bandera) %>% 
  filter(tipo_bandera == "PROPIA PECSA") %>% 
  pull(distrito)

distritos_con_primax <- data_total %>% 
  distinct(distrito, tipo_bandera) %>% 
  filter(tipo_bandera == "PROPIA PRIMAX") %>% 
  pull(distrito)
```


# Gráfica original

```{r}
data_total_semanal %>% 
    filter(
           codigo_de_osinergmin %ni% lista_vecinos,
           fecha >= dmy("01/07/2017") & fecha <= dmy("01/11/2018")) %>% 
    mutate(producto = fct_relevel(producto,c("G90","DIESEL")),
           pecsa_no = case_when(
             tipo_bandera == "PROPIA PECSA" ~ "PECSA",
             tipo_bandera == "PROPIA PRIMAX" ~ "PRIMAX",
             TRUE ~ "NO VECINOS")) %>% 
    filter(producto == "G90") %>% 
    group_by(fecha, pecsa_no) %>% 
    summarise(precio_promedio = mean(precio_de_venta), .groups = "drop") %>% 
    group_by(pecsa_no) %>% 
    tq_mutate(
        # tq_mutate args
        select     = precio_promedio,
        mutate_fun = rollapply, 
        # rollapply args
        width      = 4,
        align      = "right",
        FUN        = mean,
        # mean args
        na.rm      = TRUE,
        # tq_mutate args
        col_rename = "media_movil"
    ) %>% 
    ggplot() +
    geom_line(aes(x = fecha, y = media_movil, color = pecsa_no),
              size = 1) +
    labs(x = "Fecha", 
         y = "Precio promedio", 
         color = "Estaciones",
         title = "Precios promedio de Gasohol 90") +
    tema_grafica +
    formato_comun + 
    scale_color_manual(values=c("#2ecc71", "#e74c3c", "#f1c40f"))
```

# Gráfica de gasohol
Solo Primax y sus vecinas y no vecinas

```{r}
(p_primax_g90 <- data_total_semanal %>%
  filter(
    fecha >= dmy("01/07/2017") & fecha <= dmy("01/11/2018"),
    tipo_bandera != "PROPIA PECSA",
    tipo_bandera == "PROPIA PRIMAX" | vecino_pecsa_thiessen == 0,
  ) %>%
  mutate(
    primax_no = case_when(
      tipo_bandera == "PROPIA PRIMAX" ~ "PRIMAX",
      vecino_primax_thiessen == 1 ~ "VECINA",
      TRUE ~ "NO VECINA"
    ),
    primax_no = fct_relevel(primax_no, "PRIMAX", "VECINA")
  ) %>%
  filter(producto == "G90") %>%
  group_by(fecha, primax_no) %>%
  summarise(precio_promedio = mean(precio_de_venta),
            .groups = "drop") %>%
  group_by(primax_no) %>%
  tq_mutate(
    # tq_mutate args
    select = precio_promedio,
    mutate_fun = rollapply,
    # rollapply args
    width = 4,
    align = "right",
    FUN = mean,
    # mean args
    na.rm = TRUE,
    # tq_mutate args
    col_rename = "media_movil"
  ) %>%
  ggplot() +
  geom_line(aes(x = fecha, y = media_movil, color = primax_no),
    size = 1
  ) +
  labs(
    x = NULL,
    y = "Precio promedio (soles / galón)",
    color = "",
    title = "Evolución de precios de Primax"
  ) +
  tema_grafica +
  formato_comun +
  scale_color_manual(
    values = cols1,
    labels = c(paste("PRIMAX","\n(",tabla_vecinos$n[tabla_vecinos$tabla == "PRIMAX"],")", sep = ""),
               paste("VECINAS A PRIMAX","\n(",tabla_vecinos$n[tabla_vecinos$tabla == "SOLO VECINA A PRIMAX"], ")", sep = "" ),
               paste("NO VECINAS A NINGUNA","\n(",tabla_vecinos$n[tabla_vecinos$tabla == "NO VECINA A NINGUNA"], ")", sep = ""))
    ) + 
 theme(legend.text = element_text(size = 7))
 )
```

```{r}
(p_pecsa_g90 <- data_total_semanal %>%
  filter(
    fecha >= dmy("01/07/2017") & fecha <= dmy("01/11/2018"),
    tipo_bandera != "PROPIA PRIMAX",
    tipo_bandera == "PROPIA PECSA" | vecino_primax_thiessen == 0,
    producto == "G90",
  ) %>%
  mutate(
    pecsa_no = case_when(
      tipo_bandera == "PROPIA PECSA" ~ "PECSA",
      vecino_pecsa_thiessen == 1 ~ "VECINA",
      TRUE ~ "NO VECINA"
    ),
    pecsa_no = fct_relevel(pecsa_no, "PECSA", "VECINA")
  ) %>%
  group_by(fecha, pecsa_no) %>%
  summarise(precio_promedio = mean(precio_de_venta), .groups = "drop") %>%
  group_by(pecsa_no) %>%
  tq_mutate(
    # tq_mutate args
    select = precio_promedio,
    mutate_fun = rollapply,
    # rollapply args
    width = 4,
    align = "right",
    FUN = mean,
    # mean args
    na.rm = TRUE,
    # tq_mutate args
    col_rename = "media_movil"
  ) %>%
  ggplot() +
  geom_line(aes(x = fecha, y = media_movil, color = pecsa_no),
    size = 1
  ) +
  labs(
    x = NULL,
    y = NULL,
    color = "",
    title = "Evolución de precios de Pecsa"
  ) +
  tema_grafica +
  formato_comun +
  scale_color_manual(
    values = cols1,
    labels = c(paste("PECSA","\n(",tabla_vecinos$n[tabla_vecinos$tabla == "PECSA"],")", sep = ""),
               paste("VECINAS A PECSA","\n(",tabla_vecinos$n[tabla_vecinos$tabla == "SOLO VECINA A PECSA"], ")", sep = "" ),
               paste("NO VECINAS A NINGUNA","\n(",tabla_vecinos$n[tabla_vecinos$tabla == "NO VECINA A NINGUNA"], ")", sep = ""))
    ) +
 theme(legend.text = element_text(size = 7))
) 

p_primax_g90 + p_pecsa_g90 + plot_annotation(
  caption = "Entre paréntesis se muestran el total de estaciones en cada grupo.")
ggsave(filename = "doc/figures/precios-g90-comparacion.png", 
       height = 3, width = 5.5, scale = 1.5)

```


# Gráfica de diesel

```{r}
(p_primax_diesel <- data_total_semanal %>%
  filter(
    fecha >= dmy("01/07/2017") & fecha <= dmy("01/11/2018"),
    tipo_bandera != "PROPIA PECSA",
    tipo_bandera == "PROPIA PRIMAX" | vecino_pecsa_thiessen == 0,
  ) %>%
  mutate(
    primax_no = case_when(
      tipo_bandera == "PROPIA PRIMAX" ~ "PRIMAX",
      vecino_primax_thiessen == 1 ~ "VECINA",
      TRUE ~ "NO VECINA"
    ),
    primax_no = fct_relevel(primax_no, "PRIMAX", "VECINA")
  ) %>%
  filter(producto == "DIESEL") %>%
  group_by(fecha, primax_no) %>%
  summarise(precio_promedio = mean(precio_de_venta), .groups = "drop") %>%
  group_by(primax_no) %>%
  tq_mutate(
    # tq_mutate args
    select = precio_promedio,
    mutate_fun = rollapply,
    # rollapply args
    width = 4,
    align = "right",
    FUN = mean,
    # mean args
    na.rm = TRUE,
    # tq_mutate args
    col_rename = "media_movil"
  ) %>%
  ggplot() +
  geom_line(aes(x = fecha, y = media_movil, color = primax_no),
    size = 1
  ) +
  labs(
    x = NULL,
    y = "Precio promedio (soles / galón)",
    color = "",
    title = "Evolución de precios de Primax"
  ) +
  tema_grafica +
  formato_comun +
  scale_color_manual(
    values = cols1,
    labels = c(paste("PRIMAX","\n(",tabla_vecinos$n[tabla_vecinos$tabla == "PRIMAX"],")", sep = ""),
               paste("VECINAS A PRIMAX","\n(",tabla_vecinos$n[tabla_vecinos$tabla == "SOLO VECINA A PRIMAX"], ")", sep = "" ),
               paste("NO VECINAS A NINGUNA","\n(",tabla_vecinos$n[tabla_vecinos$tabla == "NO VECINA A NINGUNA"], ")", sep = ""))
    ) + 
 theme(legend.text = element_text(size = 7))
 )

```

```{r}
(p_pecsa_diesel <- data_total_semanal %>%
  filter(
    fecha >= dmy("01/07/2017") & fecha <= dmy("01/11/2018"),
    tipo_bandera != "PROPIA PRIMAX",
    tipo_bandera == "PROPIA PECSA" | vecino_primax_thiessen == 0,
    producto == "DIESEL",
  ) %>%
  mutate(
    pecsa_no = case_when(
      tipo_bandera == "PROPIA PECSA" ~ "PECSA",
      vecino_pecsa_thiessen == 1 ~ "VECINA",
      TRUE ~ "NO VECINA"
    ),
    pecsa_no = fct_relevel(pecsa_no, "PRIMAX", "PECSA", "VECINA")
  ) %>%
  group_by(fecha, pecsa_no) %>%
  summarise(precio_promedio = mean(precio_de_venta), .groups = "drop") %>%
  group_by(pecsa_no) %>%
  tq_mutate(
    # tq_mutate args
    select = precio_promedio,
    mutate_fun = rollapply,
    # rollapply args
    width = 4,
    align = "right",
    FUN = mean,
    # mean args
    na.rm = TRUE,
    # tq_mutate args
    col_rename = "media_movil"
  ) %>%
  ggplot() +
  geom_line(aes(x = fecha, y = media_movil, color = pecsa_no),
    size = 1
  ) +
  labs(
    x = NULL,
    y = NULL,
    color = "",
    title = "Evolución de precios de Pecsa"
  ) +
  tema_grafica +
  formato_comun +
  scale_color_manual(
    values = cols1,
    labels = c(paste("PECSA","\n(",tabla_vecinos$n[tabla_vecinos$tabla == "PECSA"],")", sep = ""),
               paste("VECINAS A PECSA","\n(",tabla_vecinos$n[tabla_vecinos$tabla == "SOLO VECINA A PECSA"], ")", sep = "" ),
               paste("NO VECINAS A NINGUNA","\n(",tabla_vecinos$n[tabla_vecinos$tabla == "NO VECINA A NINGUNA"], ")", sep = ""))
    ) +
 theme(legend.text = element_text(size = 7))
) 

p_primax_diesel + p_pecsa_diesel + plot_annotation(
  caption = "Entre paréntesis se muestran el total de estaciones en cada grupo.")

ggsave(filename = "doc/figures/precios-diesel-comparacion.png", 
       height = 3, width = 5.5, scale = 1.5)



```

# Tabla de estaciones

Tabla contando estaciones

```{r}
tabla_vecinos <- data_total_mensual %>% 
  distinct(codigo_de_osinergmin, .keep_all = T) %>% 
  mutate(tabla = case_when(
    tipo_bandera == "PROPIA PRIMAX" ~ "PRIMAX",
    tipo_bandera == "PROPIA PECSA" ~ "PECSA",
    vecino_pecsa_thiessen == 1 & vecino_primax_thiessen == 1 ~ "VECINA A AMBOS",
    vecino_pecsa_thiessen == 1 ~ "SOLO VECINA A PECSA",
    vecino_primax_thiessen == 1 ~ "SOLO VECINA A PRIMAX",
    TRUE ~ "NO VECINA A NINGUNA"
  ),
  tabla = fct_relevel(factor(tabla), "PRIMAX", "PECSA", 
                      "SOLO VECINA A PRIMAX", "SOLO VECINA A PECSA",
                      "VECINA A AMBOS", "NO VECINA A NINGUNA")
  ) %>% 
  count(tabla) 

tabla_vecinos
```

Tabla con precios según vecindad

```{r}
data_total_mensual %>% 
  mutate(tabla = case_when(
    tipo_bandera == "PROPIA PRIMAX" ~ "PRIMAX",
    tipo_bandera == "PROPIA PECSA" ~ "PECSA",
    vecino_pecsa_thiessen == 1 & vecino_primax_thiessen == 1 ~ "VECINA A AMBOS",
    vecino_pecsa_thiessen == 1 ~ "SOLO VECINA A PECSA",
    vecino_primax_thiessen == 1 ~ "SOLO VECINA A PRIMAX",
    TRUE ~ "NO VECINA A NINGUNA"
  ),
  tabla = fct_relevel(factor(tabla), "PRIMAX", "PECSA", 
                      "SOLO VECINA A PRIMAX", "SOLO VECINA A PECSA",
                      "VECINA A AMBOS", "NO VECINA A NINGUNA")
  ) %>% 
  group_by(tabla) %>% 
  summarise(Precio = mean(precio_de_venta))
```

Tabla con precios según bandera

```{r}
resumen_g90 <- data_total_mensual %>%
  mutate(
    tabla = case_when(
      tipo_bandera == "PROPIA PRIMAX" ~ "PRIMAX",
      tipo_bandera == "PROPIA PECSA" ~ "PECSA",
      tipo_bandera == "PROPIA REPSOL" ~ "REPSOL",
      str_detect(tipo_bandera, "ABANDERADA") ~ "ABANDERADA",
      TRUE ~ "INDEPENDIENTE"
    ),
    tabla = fct_relevel(
      factor(tabla), "PRIMAX", "PECSA",
      "REPSOL", "ABANDERADA"
    )
  ) %>%
  group_by(tabla, producto) %>%
  summarise(Obs = n(), Precio = mean(precio_de_venta), 
            Std = sd(precio_de_venta), Min. = min(precio_de_venta), 
            Max. = max(precio_de_venta)) %>% 
  filter(producto == "G90") %>% 
  select(-producto)

resumen_diesel <- data_total_mensual %>%
  mutate(
    tabla = case_when(
      tipo_bandera == "PROPIA PRIMAX" ~ "PRIMAX",
      tipo_bandera == "PROPIA PECSA" ~ "PECSA",
      tipo_bandera == "PROPIA REPSOL" ~ "REPSOL",
      str_detect(tipo_bandera, "ABANDERADA") ~ "ABANDERADA",
      TRUE ~ "INDEPENDIENTE"
    ),
    tabla = fct_relevel(
      factor(tabla), "PRIMAX", "PECSA",
      "REPSOL", "ABANDERADA"
    )
  ) %>%
  group_by(tabla, producto) %>%
  summarise(Obs = n(), Precio = mean(precio_de_venta), 
            Std = sd(precio_de_venta), Min. = min(precio_de_venta), 
            Max. = max(precio_de_venta)) %>% 
  filter(producto == "DIESEL") %>% 
  select(-producto, -Obs)

tipos_estaciones <- data_total_mensual %>%
  distinct(codigo_de_osinergmin, .keep_all = T) %>% 
  mutate(
    tabla = case_when(
      tipo_bandera == "PROPIA PRIMAX" ~ "PRIMAX",
      tipo_bandera == "PROPIA PECSA" ~ "PECSA",
      tipo_bandera == "PROPIA REPSOL" ~ "REPSOL",
      str_detect(tipo_bandera, "ABANDERADA") ~ "ABANDERADA",
      TRUE ~ "INDEPENDIENTE"
    ),
    tabla = fct_relevel(
      factor(tabla), "PRIMAX", "PECSA",
      "REPSOL", "ABANDERADA"
    )
  ) %>% 
  count(tabla)

tabla2 <- full_join(resumen_g90, resumen_diesel, by = "tabla", suffix = c("_G90", "_DIESEL")) %>% 
  full_join(tipos_estaciones, by = "tabla") %>% 
  select(tabla, n, everything())

tabla2



colnames(tabla2)

my_header <- data.frame(
  col_keys = colnames(tabla2),
  line1 = c("", "", "",  rep("Gasohol 90", 4), rep("Diésel", 4)),
  line2 = c("Tipo de Estación", "Nº Estaciones", "Obs.", 
            "Precio", "SD", "Min.", "Max.", 
            "Precio", "SD", "Min.", "Max."),
  stringsAsFactors = FALSE
)

set_flextable_defaults(
  font.family = "Times New Roman", 
  font.size = 10,
  font.color = "black",
  table.layout = "fixed",
  digits = 1,
  theme_fun = "theme_box"
  )

tabla2 %>%
  mutate(tabla = str_to_title(tabla)) %>% 
  flextable(col_keys = my_header$col_keys) %>% 
  set_header_df(mapping = my_header, key = "col_keys") %>%
  colformat_double(j = colnames(tabla2)[3:11], digits = 2 ) %>% 
  theme_booktabs() %>% 
  merge_v(part = "header") %>%
  merge_h(part = "header") %>%
  align(align = "center", part = "all") %>% 
  set_table_properties( width = .5, layout = "autofit") %>% 
  print(preview = "docx")
```


# Gráfica market share


```{r}
data_total_mensual %>%
  distinct(codigo_de_osinergmin, .keep_all = T) %>% 
  select(codigo_de_osinergmin, tipo, bandera) %>% 
  group_by(tipo, bandera) %>% 
  summarise(count = n()) %>% 
  ungroup() %>% 
  mutate(perc = count/sum(count),
         tipo = fct_relevel(tipo, "PROPIA", "ABANDERADA")) %>% 
  ggplot(aes(x = bandera, y = perc)) + 
  geom_col(aes(fill = tipo), width = 0.5) + 
  coord_flip() +
  scale_y_continuous(breaks = c(0,0.10,0.2,0.3), 
                     labels = scales::percent,
                     limits = c(0,0.3)) +
  labs(y = "Participación en el mercado minorista por cantidad de estaciones (%)", 
       x = NULL,
       fill = "Tipo de estación") + 
  scale_fill_brewer(type = "qual", direction = -1) + 
  theme_minimal() + 
  theme(axis.text = element_text(
    size = 12, lineheight = .9,
    face = "bold"
  ))
  ggsave(filename = "doc/figures/market-share-lima.png", 
       height = 3, width = 5.5, scale = 1.5)

data_total_mensual %>%
  distinct(codigo_de_osinergmin, .keep_all = T) %>% 
  select(codigo_de_osinergmin, tipo, bandera) %>% 
  group_by(tipo, bandera) %>% 
  summarise(count = n()) %>% 
  ungroup() %>% 
  mutate(perc = count/sum(count),
         tipo = fct_relevel(tipo, "PROPIA", "ABANDERADA")) 

data_total_mensual %>%
  distinct(codigo_de_osinergmin, .keep_all = T) %>% 
  select(codigo_de_osinergmin, tipo, bandera) %>% 
  group_by(tipo) %>% 
  summarise(count = n()) %>% 
  ungroup() %>% 
  mutate(perc = count/sum(count))
```
